export const SIZE_VARIANT = {
    DISPLAY_XL: { fontSize: 48, fontWeight: 600 },
    DISPLAY_LG: { fontSize: 44, fontWeight: 600 },
    DISPLAY_MD: { fontSize: 40, fontWeight: 600 },
    DISPLAY_SM: { fontSize: 32, fontWeight: 600 },
    TITLE_XL: { fontSize: 32, fontWeight: 500 },
    TITLE_LG: { fontSize: 28, fontWeight: 500 },
    TITLE_MD: { fontSize: 24, fontWeight: 500 },
    TITLE_SM: { fontSize: 20, fontWeight: 500 },
    TITLE_XS: { fontSize: 16, fontWeight: 500 },
    SUBTITLE_LG: { fontSize: 20, fontWeight: 400 },
    SUBTITLE_MD: { fontSize: 18, fontWeight: 400 },
    SUBTITLE_SM: { fontSize: 16, fontWeight: 400 },
    BODY_LG_NORMAL: { fontSize: 16, fontWeight: 400 },
    BODY_MD_NORMAL: { fontSize: 14, fontWeight: 400 },
    BODY_SM_NORMAL: { fontSize: 12, fontWeight: 400 },
    BODY_LG_BOLDEST: { fontSize: 16, fontWeight: 500 },
    BODY_MD_BOLDEST: { fontSize: 14, fontWeight: 500 },
    BODY_SM_BOLDEST: { fontSize: 12, fontWeight: 500 },
    LABEL_LG_NORMAL: { fontSize: 16, fontWeight: 400 },
    LABEL_MD_NORMAL: { fontSize: 14, fontWeight: 400 },
    LABEL_SM_NORMAL: { fontSize: 12, fontWeight: 400 },
    LABEL_LG_BOLDEST: { fontSize: 16, fontWeight: 500 },
    LABEL_MD_BOLDEST: { fontSize: 14, fontWeight: 500 },
    LABEL_SM_BOLDEST: { fontSize: 12, fontWeight: 500 },
    HELPER_TEXT_LG: { fontSize: 14, fontWeight: 400 },
    HELPER_TEXT_MD: { fontSize: 12, fontWeight: 400 },
    HELPER_TEXT_SM: { fontSize: 10, fontWeight: 400 },
    TABLE_HEADER: {
        fontSize: 14,
        fontWeight: 600,
        textTransform: 'uppercase',
        letterSpacing: '0.1em',
    },
};