export enum FilterType {
  SEARCH = 'SEARCH',
  SELECT = 'SELECT',
  MULTI_SELECT = 'MULTI_SELECT',
  DATE = 'DATE',
  DATE_TIME = 'DATE_TIME',
  YEAR = 'YEAR',
  MONTH_YEAR = 'MONTH_YEAR',
  TIME = 'TIME',
  DATE_RANGE = 'DATE_RANGE',
  CHECKBOX = 'CHECKBOX'
}

export enum DataViewControllerType {
  BUTTON_GROUP = 'BUTTON_GROUP',
  SELECT = 'SELECT'
}
